<?xml version="1.0" encoding="utf-8"?><Database Name="mysqlserver" Class="dbDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=mysqlserver3216514.database.windows.net;Initial Catalog=mysqlserver;Persist Security Info=True;User ID=sqladmin" SettingsObjectName="Datos.Properties.Settings" SettingsPropertyName="mysqlserverConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.empleado" Member="empleados">
    <Type Name="empleado">
      <Column Name="codigo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombre" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="apellidoMaterno" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="apellidoPaterno" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="identificacion" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="fechaNace" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="email" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="rol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="usuario" Type="System.String" DbType="VarChar(12) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="contrasena" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="codigoLog" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="empleado_materia" Member="materias" ThisKey="usuario" OtherKey="usuarioEmple" Type="materia" />
    </Type>
  </Table>
  <Table Name="dbo.estudiante" Member="estudiantes">
    <Type Name="estudiante">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nombreE" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="apellidoMaterno" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="apellidoPaterno" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="identificacion" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="direccion" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="usuario" Type="System.String" DbType="VarChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="contrasena" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="telefono" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="fechaNaci" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="rol" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="estudiante_matricula" Member="matriculas" ThisKey="usuario" OtherKey="usuarioEst" Type="matricula" />
    </Type>
  </Table>
  <Table Name="dbo.materia" Member="materias">
    <Type Name="materia">
      <Column Name="codigo" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="nombreM" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="usuarioEmple" Type="System.String" DbType="VarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="estado" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="materia_matricula" Member="matriculas" ThisKey="codigo" OtherKey="codigoMateria" Type="matricula" />
      <Association Name="empleado_materia" Member="empleado" ThisKey="usuarioEmple" OtherKey="usuario" Type="empleado" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.matricula" Member="matriculas">
    <Type Name="matricula">
      <Column Name="numero" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="codigoMateria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="usuarioEst" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="materia_matricula" Member="materia" ThisKey="codigoMateria" OtherKey="codigo" Type="materia" IsForeignKey="true" />
      <Association Name="estudiante_matricula" Member="estudiante" ThisKey="usuarioEst" OtherKey="usuario" Type="estudiante" IsForeignKey="true" />
    </Type>
  </Table>
</Database>